
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BarberShop` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BarberShop
 * 
 */
export type BarberShopModel = runtime.Types.Result.DefaultSelection<Prisma.$BarberShopPayload>

export type AggregateBarberShop = {
  _count: BarberShopCountAggregateOutputType | null
  _min: BarberShopMinAggregateOutputType | null
  _max: BarberShopMaxAggregateOutputType | null
}

export type BarberShopMinAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  address: string | null
  phone: string | null
  imageUrl: string | null
  ownerId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BarberShopMaxAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  address: string | null
  phone: string | null
  imageUrl: string | null
  ownerId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BarberShopCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  address: number
  phone: number
  imageUrl: number
  ownerId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BarberShopMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  address?: true
  phone?: true
  imageUrl?: true
  ownerId?: true
  createdAt?: true
  updatedAt?: true
}

export type BarberShopMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  address?: true
  phone?: true
  imageUrl?: true
  ownerId?: true
  createdAt?: true
  updatedAt?: true
}

export type BarberShopCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  address?: true
  phone?: true
  imageUrl?: true
  ownerId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BarberShopAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BarberShop to aggregate.
   */
  where?: Prisma.BarberShopWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarberShops to fetch.
   */
  orderBy?: Prisma.BarberShopOrderByWithRelationInput | Prisma.BarberShopOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BarberShopWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarberShops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarberShops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BarberShops
  **/
  _count?: true | BarberShopCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BarberShopMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BarberShopMaxAggregateInputType
}

export type GetBarberShopAggregateType<T extends BarberShopAggregateArgs> = {
      [P in keyof T & keyof AggregateBarberShop]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBarberShop[P]>
    : Prisma.GetScalarType<T[P], AggregateBarberShop[P]>
}




export type BarberShopGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BarberShopWhereInput
  orderBy?: Prisma.BarberShopOrderByWithAggregationInput | Prisma.BarberShopOrderByWithAggregationInput[]
  by: Prisma.BarberShopScalarFieldEnum[] | Prisma.BarberShopScalarFieldEnum
  having?: Prisma.BarberShopScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BarberShopCountAggregateInputType | true
  _min?: BarberShopMinAggregateInputType
  _max?: BarberShopMaxAggregateInputType
}

export type BarberShopGroupByOutputType = {
  id: string
  name: string
  slug: string
  address: string
  phone: string | null
  imageUrl: string | null
  ownerId: string
  createdAt: Date
  updatedAt: Date
  _count: BarberShopCountAggregateOutputType | null
  _min: BarberShopMinAggregateOutputType | null
  _max: BarberShopMaxAggregateOutputType | null
}

type GetBarberShopGroupByPayload<T extends BarberShopGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BarberShopGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BarberShopGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BarberShopGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BarberShopGroupByOutputType[P]>
      }
    >
  >



export type BarberShopWhereInput = {
  AND?: Prisma.BarberShopWhereInput | Prisma.BarberShopWhereInput[]
  OR?: Prisma.BarberShopWhereInput[]
  NOT?: Prisma.BarberShopWhereInput | Prisma.BarberShopWhereInput[]
  id?: Prisma.StringFilter<"BarberShop"> | string
  name?: Prisma.StringFilter<"BarberShop"> | string
  slug?: Prisma.StringFilter<"BarberShop"> | string
  address?: Prisma.StringFilter<"BarberShop"> | string
  phone?: Prisma.StringNullableFilter<"BarberShop"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"BarberShop"> | string | null
  ownerId?: Prisma.StringFilter<"BarberShop"> | string
  createdAt?: Prisma.DateTimeFilter<"BarberShop"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BarberShop"> | Date | string
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  services?: Prisma.ServiceListRelationFilter
  bookings?: Prisma.BookingListRelationFilter
}

export type BarberShopOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  address?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  owner?: Prisma.UserOrderByWithRelationInput
  services?: Prisma.ServiceOrderByRelationAggregateInput
  bookings?: Prisma.BookingOrderByRelationAggregateInput
}

export type BarberShopWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.BarberShopWhereInput | Prisma.BarberShopWhereInput[]
  OR?: Prisma.BarberShopWhereInput[]
  NOT?: Prisma.BarberShopWhereInput | Prisma.BarberShopWhereInput[]
  name?: Prisma.StringFilter<"BarberShop"> | string
  address?: Prisma.StringFilter<"BarberShop"> | string
  phone?: Prisma.StringNullableFilter<"BarberShop"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"BarberShop"> | string | null
  ownerId?: Prisma.StringFilter<"BarberShop"> | string
  createdAt?: Prisma.DateTimeFilter<"BarberShop"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BarberShop"> | Date | string
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  services?: Prisma.ServiceListRelationFilter
  bookings?: Prisma.BookingListRelationFilter
}, "id" | "slug">

export type BarberShopOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  address?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BarberShopCountOrderByAggregateInput
  _max?: Prisma.BarberShopMaxOrderByAggregateInput
  _min?: Prisma.BarberShopMinOrderByAggregateInput
}

export type BarberShopScalarWhereWithAggregatesInput = {
  AND?: Prisma.BarberShopScalarWhereWithAggregatesInput | Prisma.BarberShopScalarWhereWithAggregatesInput[]
  OR?: Prisma.BarberShopScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BarberShopScalarWhereWithAggregatesInput | Prisma.BarberShopScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BarberShop"> | string
  name?: Prisma.StringWithAggregatesFilter<"BarberShop"> | string
  slug?: Prisma.StringWithAggregatesFilter<"BarberShop"> | string
  address?: Prisma.StringWithAggregatesFilter<"BarberShop"> | string
  phone?: Prisma.StringNullableWithAggregatesFilter<"BarberShop"> | string | null
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"BarberShop"> | string | null
  ownerId?: Prisma.StringWithAggregatesFilter<"BarberShop"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BarberShop"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BarberShop"> | Date | string
}

export type BarberShopCreateInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutBarberShopsInput
  services?: Prisma.ServiceCreateNestedManyWithoutBarberShopInput
  bookings?: Prisma.BookingCreateNestedManyWithoutBarberShopInput
}

export type BarberShopUncheckedCreateInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  ownerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  services?: Prisma.ServiceUncheckedCreateNestedManyWithoutBarberShopInput
  bookings?: Prisma.BookingUncheckedCreateNestedManyWithoutBarberShopInput
}

export type BarberShopUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutBarberShopsNestedInput
  services?: Prisma.ServiceUpdateManyWithoutBarberShopNestedInput
  bookings?: Prisma.BookingUpdateManyWithoutBarberShopNestedInput
}

export type BarberShopUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  services?: Prisma.ServiceUncheckedUpdateManyWithoutBarberShopNestedInput
  bookings?: Prisma.BookingUncheckedUpdateManyWithoutBarberShopNestedInput
}

export type BarberShopCreateManyInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  ownerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BarberShopUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BarberShopUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BarberShopListRelationFilter = {
  every?: Prisma.BarberShopWhereInput
  some?: Prisma.BarberShopWhereInput
  none?: Prisma.BarberShopWhereInput
}

export type BarberShopOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BarberShopCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  address?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BarberShopMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  address?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BarberShopMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  address?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BarberShopScalarRelationFilter = {
  is?: Prisma.BarberShopWhereInput
  isNot?: Prisma.BarberShopWhereInput
}

export type BarberShopCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.BarberShopCreateWithoutOwnerInput, Prisma.BarberShopUncheckedCreateWithoutOwnerInput> | Prisma.BarberShopCreateWithoutOwnerInput[] | Prisma.BarberShopUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.BarberShopCreateOrConnectWithoutOwnerInput | Prisma.BarberShopCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.BarberShopCreateManyOwnerInputEnvelope
  connect?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
}

export type BarberShopUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.BarberShopCreateWithoutOwnerInput, Prisma.BarberShopUncheckedCreateWithoutOwnerInput> | Prisma.BarberShopCreateWithoutOwnerInput[] | Prisma.BarberShopUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.BarberShopCreateOrConnectWithoutOwnerInput | Prisma.BarberShopCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.BarberShopCreateManyOwnerInputEnvelope
  connect?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
}

export type BarberShopUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.BarberShopCreateWithoutOwnerInput, Prisma.BarberShopUncheckedCreateWithoutOwnerInput> | Prisma.BarberShopCreateWithoutOwnerInput[] | Prisma.BarberShopUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.BarberShopCreateOrConnectWithoutOwnerInput | Prisma.BarberShopCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.BarberShopUpsertWithWhereUniqueWithoutOwnerInput | Prisma.BarberShopUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.BarberShopCreateManyOwnerInputEnvelope
  set?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
  disconnect?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
  delete?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
  connect?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
  update?: Prisma.BarberShopUpdateWithWhereUniqueWithoutOwnerInput | Prisma.BarberShopUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.BarberShopUpdateManyWithWhereWithoutOwnerInput | Prisma.BarberShopUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.BarberShopScalarWhereInput | Prisma.BarberShopScalarWhereInput[]
}

export type BarberShopUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.BarberShopCreateWithoutOwnerInput, Prisma.BarberShopUncheckedCreateWithoutOwnerInput> | Prisma.BarberShopCreateWithoutOwnerInput[] | Prisma.BarberShopUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.BarberShopCreateOrConnectWithoutOwnerInput | Prisma.BarberShopCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.BarberShopUpsertWithWhereUniqueWithoutOwnerInput | Prisma.BarberShopUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.BarberShopCreateManyOwnerInputEnvelope
  set?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
  disconnect?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
  delete?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
  connect?: Prisma.BarberShopWhereUniqueInput | Prisma.BarberShopWhereUniqueInput[]
  update?: Prisma.BarberShopUpdateWithWhereUniqueWithoutOwnerInput | Prisma.BarberShopUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.BarberShopUpdateManyWithWhereWithoutOwnerInput | Prisma.BarberShopUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.BarberShopScalarWhereInput | Prisma.BarberShopScalarWhereInput[]
}

export type BarberShopCreateNestedOneWithoutServicesInput = {
  create?: Prisma.XOR<Prisma.BarberShopCreateWithoutServicesInput, Prisma.BarberShopUncheckedCreateWithoutServicesInput>
  connectOrCreate?: Prisma.BarberShopCreateOrConnectWithoutServicesInput
  connect?: Prisma.BarberShopWhereUniqueInput
}

export type BarberShopUpdateOneRequiredWithoutServicesNestedInput = {
  create?: Prisma.XOR<Prisma.BarberShopCreateWithoutServicesInput, Prisma.BarberShopUncheckedCreateWithoutServicesInput>
  connectOrCreate?: Prisma.BarberShopCreateOrConnectWithoutServicesInput
  upsert?: Prisma.BarberShopUpsertWithoutServicesInput
  connect?: Prisma.BarberShopWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BarberShopUpdateToOneWithWhereWithoutServicesInput, Prisma.BarberShopUpdateWithoutServicesInput>, Prisma.BarberShopUncheckedUpdateWithoutServicesInput>
}

export type BarberShopCreateNestedOneWithoutBookingsInput = {
  create?: Prisma.XOR<Prisma.BarberShopCreateWithoutBookingsInput, Prisma.BarberShopUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.BarberShopCreateOrConnectWithoutBookingsInput
  connect?: Prisma.BarberShopWhereUniqueInput
}

export type BarberShopUpdateOneRequiredWithoutBookingsNestedInput = {
  create?: Prisma.XOR<Prisma.BarberShopCreateWithoutBookingsInput, Prisma.BarberShopUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.BarberShopCreateOrConnectWithoutBookingsInput
  upsert?: Prisma.BarberShopUpsertWithoutBookingsInput
  connect?: Prisma.BarberShopWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BarberShopUpdateToOneWithWhereWithoutBookingsInput, Prisma.BarberShopUpdateWithoutBookingsInput>, Prisma.BarberShopUncheckedUpdateWithoutBookingsInput>
}

export type BarberShopCreateWithoutOwnerInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  services?: Prisma.ServiceCreateNestedManyWithoutBarberShopInput
  bookings?: Prisma.BookingCreateNestedManyWithoutBarberShopInput
}

export type BarberShopUncheckedCreateWithoutOwnerInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  services?: Prisma.ServiceUncheckedCreateNestedManyWithoutBarberShopInput
  bookings?: Prisma.BookingUncheckedCreateNestedManyWithoutBarberShopInput
}

export type BarberShopCreateOrConnectWithoutOwnerInput = {
  where: Prisma.BarberShopWhereUniqueInput
  create: Prisma.XOR<Prisma.BarberShopCreateWithoutOwnerInput, Prisma.BarberShopUncheckedCreateWithoutOwnerInput>
}

export type BarberShopCreateManyOwnerInputEnvelope = {
  data: Prisma.BarberShopCreateManyOwnerInput | Prisma.BarberShopCreateManyOwnerInput[]
}

export type BarberShopUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.BarberShopWhereUniqueInput
  update: Prisma.XOR<Prisma.BarberShopUpdateWithoutOwnerInput, Prisma.BarberShopUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.BarberShopCreateWithoutOwnerInput, Prisma.BarberShopUncheckedCreateWithoutOwnerInput>
}

export type BarberShopUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.BarberShopWhereUniqueInput
  data: Prisma.XOR<Prisma.BarberShopUpdateWithoutOwnerInput, Prisma.BarberShopUncheckedUpdateWithoutOwnerInput>
}

export type BarberShopUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.BarberShopScalarWhereInput
  data: Prisma.XOR<Prisma.BarberShopUpdateManyMutationInput, Prisma.BarberShopUncheckedUpdateManyWithoutOwnerInput>
}

export type BarberShopScalarWhereInput = {
  AND?: Prisma.BarberShopScalarWhereInput | Prisma.BarberShopScalarWhereInput[]
  OR?: Prisma.BarberShopScalarWhereInput[]
  NOT?: Prisma.BarberShopScalarWhereInput | Prisma.BarberShopScalarWhereInput[]
  id?: Prisma.StringFilter<"BarberShop"> | string
  name?: Prisma.StringFilter<"BarberShop"> | string
  slug?: Prisma.StringFilter<"BarberShop"> | string
  address?: Prisma.StringFilter<"BarberShop"> | string
  phone?: Prisma.StringNullableFilter<"BarberShop"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"BarberShop"> | string | null
  ownerId?: Prisma.StringFilter<"BarberShop"> | string
  createdAt?: Prisma.DateTimeFilter<"BarberShop"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BarberShop"> | Date | string
}

export type BarberShopCreateWithoutServicesInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutBarberShopsInput
  bookings?: Prisma.BookingCreateNestedManyWithoutBarberShopInput
}

export type BarberShopUncheckedCreateWithoutServicesInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  ownerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  bookings?: Prisma.BookingUncheckedCreateNestedManyWithoutBarberShopInput
}

export type BarberShopCreateOrConnectWithoutServicesInput = {
  where: Prisma.BarberShopWhereUniqueInput
  create: Prisma.XOR<Prisma.BarberShopCreateWithoutServicesInput, Prisma.BarberShopUncheckedCreateWithoutServicesInput>
}

export type BarberShopUpsertWithoutServicesInput = {
  update: Prisma.XOR<Prisma.BarberShopUpdateWithoutServicesInput, Prisma.BarberShopUncheckedUpdateWithoutServicesInput>
  create: Prisma.XOR<Prisma.BarberShopCreateWithoutServicesInput, Prisma.BarberShopUncheckedCreateWithoutServicesInput>
  where?: Prisma.BarberShopWhereInput
}

export type BarberShopUpdateToOneWithWhereWithoutServicesInput = {
  where?: Prisma.BarberShopWhereInput
  data: Prisma.XOR<Prisma.BarberShopUpdateWithoutServicesInput, Prisma.BarberShopUncheckedUpdateWithoutServicesInput>
}

export type BarberShopUpdateWithoutServicesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutBarberShopsNestedInput
  bookings?: Prisma.BookingUpdateManyWithoutBarberShopNestedInput
}

export type BarberShopUncheckedUpdateWithoutServicesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bookings?: Prisma.BookingUncheckedUpdateManyWithoutBarberShopNestedInput
}

export type BarberShopCreateWithoutBookingsInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutBarberShopsInput
  services?: Prisma.ServiceCreateNestedManyWithoutBarberShopInput
}

export type BarberShopUncheckedCreateWithoutBookingsInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  ownerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  services?: Prisma.ServiceUncheckedCreateNestedManyWithoutBarberShopInput
}

export type BarberShopCreateOrConnectWithoutBookingsInput = {
  where: Prisma.BarberShopWhereUniqueInput
  create: Prisma.XOR<Prisma.BarberShopCreateWithoutBookingsInput, Prisma.BarberShopUncheckedCreateWithoutBookingsInput>
}

export type BarberShopUpsertWithoutBookingsInput = {
  update: Prisma.XOR<Prisma.BarberShopUpdateWithoutBookingsInput, Prisma.BarberShopUncheckedUpdateWithoutBookingsInput>
  create: Prisma.XOR<Prisma.BarberShopCreateWithoutBookingsInput, Prisma.BarberShopUncheckedCreateWithoutBookingsInput>
  where?: Prisma.BarberShopWhereInput
}

export type BarberShopUpdateToOneWithWhereWithoutBookingsInput = {
  where?: Prisma.BarberShopWhereInput
  data: Prisma.XOR<Prisma.BarberShopUpdateWithoutBookingsInput, Prisma.BarberShopUncheckedUpdateWithoutBookingsInput>
}

export type BarberShopUpdateWithoutBookingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutBarberShopsNestedInput
  services?: Prisma.ServiceUpdateManyWithoutBarberShopNestedInput
}

export type BarberShopUncheckedUpdateWithoutBookingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  services?: Prisma.ServiceUncheckedUpdateManyWithoutBarberShopNestedInput
}

export type BarberShopCreateManyOwnerInput = {
  id?: string
  name: string
  slug: string
  address: string
  phone?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BarberShopUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  services?: Prisma.ServiceUpdateManyWithoutBarberShopNestedInput
  bookings?: Prisma.BookingUpdateManyWithoutBarberShopNestedInput
}

export type BarberShopUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  services?: Prisma.ServiceUncheckedUpdateManyWithoutBarberShopNestedInput
  bookings?: Prisma.BookingUncheckedUpdateManyWithoutBarberShopNestedInput
}

export type BarberShopUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BarberShopCountOutputType
 */

export type BarberShopCountOutputType = {
  services: number
  bookings: number
}

export type BarberShopCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  services?: boolean | BarberShopCountOutputTypeCountServicesArgs
  bookings?: boolean | BarberShopCountOutputTypeCountBookingsArgs
}

/**
 * BarberShopCountOutputType without action
 */
export type BarberShopCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShopCountOutputType
   */
  select?: Prisma.BarberShopCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BarberShopCountOutputType without action
 */
export type BarberShopCountOutputTypeCountServicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceWhereInput
}

/**
 * BarberShopCountOutputType without action
 */
export type BarberShopCountOutputTypeCountBookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BookingWhereInput
}


export type BarberShopSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  address?: boolean
  phone?: boolean
  imageUrl?: boolean
  ownerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  services?: boolean | Prisma.BarberShop$servicesArgs<ExtArgs>
  bookings?: boolean | Prisma.BarberShop$bookingsArgs<ExtArgs>
  _count?: boolean | Prisma.BarberShopCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barberShop"]>

export type BarberShopSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  address?: boolean
  phone?: boolean
  imageUrl?: boolean
  ownerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barberShop"]>

export type BarberShopSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  address?: boolean
  phone?: boolean
  imageUrl?: boolean
  ownerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barberShop"]>

export type BarberShopSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  address?: boolean
  phone?: boolean
  imageUrl?: boolean
  ownerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BarberShopOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "address" | "phone" | "imageUrl" | "ownerId" | "createdAt" | "updatedAt", ExtArgs["result"]["barberShop"]>
export type BarberShopInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  services?: boolean | Prisma.BarberShop$servicesArgs<ExtArgs>
  bookings?: boolean | Prisma.BarberShop$bookingsArgs<ExtArgs>
  _count?: boolean | Prisma.BarberShopCountOutputTypeDefaultArgs<ExtArgs>
}
export type BarberShopIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BarberShopIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BarberShopPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BarberShop"
  objects: {
    owner: Prisma.$UserPayload<ExtArgs>
    services: Prisma.$ServicePayload<ExtArgs>[]
    bookings: Prisma.$BookingPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    slug: string
    address: string
    phone: string | null
    imageUrl: string | null
    ownerId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["barberShop"]>
  composites: {}
}

export type BarberShopGetPayload<S extends boolean | null | undefined | BarberShopDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BarberShopPayload, S>

export type BarberShopCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BarberShopFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BarberShopCountAggregateInputType | true
  }

export interface BarberShopDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BarberShop'], meta: { name: 'BarberShop' } }
  /**
   * Find zero or one BarberShop that matches the filter.
   * @param {BarberShopFindUniqueArgs} args - Arguments to find a BarberShop
   * @example
   * // Get one BarberShop
   * const barberShop = await prisma.barberShop.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BarberShopFindUniqueArgs>(args: Prisma.SelectSubset<T, BarberShopFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BarberShopClient<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BarberShop that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BarberShopFindUniqueOrThrowArgs} args - Arguments to find a BarberShop
   * @example
   * // Get one BarberShop
   * const barberShop = await prisma.barberShop.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BarberShopFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BarberShopFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BarberShopClient<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BarberShop that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarberShopFindFirstArgs} args - Arguments to find a BarberShop
   * @example
   * // Get one BarberShop
   * const barberShop = await prisma.barberShop.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BarberShopFindFirstArgs>(args?: Prisma.SelectSubset<T, BarberShopFindFirstArgs<ExtArgs>>): Prisma.Prisma__BarberShopClient<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BarberShop that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarberShopFindFirstOrThrowArgs} args - Arguments to find a BarberShop
   * @example
   * // Get one BarberShop
   * const barberShop = await prisma.barberShop.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BarberShopFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BarberShopFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BarberShopClient<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BarberShops that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarberShopFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BarberShops
   * const barberShops = await prisma.barberShop.findMany()
   * 
   * // Get first 10 BarberShops
   * const barberShops = await prisma.barberShop.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const barberShopWithIdOnly = await prisma.barberShop.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BarberShopFindManyArgs>(args?: Prisma.SelectSubset<T, BarberShopFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BarberShop.
   * @param {BarberShopCreateArgs} args - Arguments to create a BarberShop.
   * @example
   * // Create one BarberShop
   * const BarberShop = await prisma.barberShop.create({
   *   data: {
   *     // ... data to create a BarberShop
   *   }
   * })
   * 
   */
  create<T extends BarberShopCreateArgs>(args: Prisma.SelectSubset<T, BarberShopCreateArgs<ExtArgs>>): Prisma.Prisma__BarberShopClient<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BarberShops.
   * @param {BarberShopCreateManyArgs} args - Arguments to create many BarberShops.
   * @example
   * // Create many BarberShops
   * const barberShop = await prisma.barberShop.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BarberShopCreateManyArgs>(args?: Prisma.SelectSubset<T, BarberShopCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BarberShops and returns the data saved in the database.
   * @param {BarberShopCreateManyAndReturnArgs} args - Arguments to create many BarberShops.
   * @example
   * // Create many BarberShops
   * const barberShop = await prisma.barberShop.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BarberShops and only return the `id`
   * const barberShopWithIdOnly = await prisma.barberShop.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BarberShopCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BarberShopCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BarberShop.
   * @param {BarberShopDeleteArgs} args - Arguments to delete one BarberShop.
   * @example
   * // Delete one BarberShop
   * const BarberShop = await prisma.barberShop.delete({
   *   where: {
   *     // ... filter to delete one BarberShop
   *   }
   * })
   * 
   */
  delete<T extends BarberShopDeleteArgs>(args: Prisma.SelectSubset<T, BarberShopDeleteArgs<ExtArgs>>): Prisma.Prisma__BarberShopClient<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BarberShop.
   * @param {BarberShopUpdateArgs} args - Arguments to update one BarberShop.
   * @example
   * // Update one BarberShop
   * const barberShop = await prisma.barberShop.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BarberShopUpdateArgs>(args: Prisma.SelectSubset<T, BarberShopUpdateArgs<ExtArgs>>): Prisma.Prisma__BarberShopClient<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BarberShops.
   * @param {BarberShopDeleteManyArgs} args - Arguments to filter BarberShops to delete.
   * @example
   * // Delete a few BarberShops
   * const { count } = await prisma.barberShop.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BarberShopDeleteManyArgs>(args?: Prisma.SelectSubset<T, BarberShopDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BarberShops.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarberShopUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BarberShops
   * const barberShop = await prisma.barberShop.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BarberShopUpdateManyArgs>(args: Prisma.SelectSubset<T, BarberShopUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BarberShops and returns the data updated in the database.
   * @param {BarberShopUpdateManyAndReturnArgs} args - Arguments to update many BarberShops.
   * @example
   * // Update many BarberShops
   * const barberShop = await prisma.barberShop.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BarberShops and only return the `id`
   * const barberShopWithIdOnly = await prisma.barberShop.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BarberShopUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BarberShopUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BarberShop.
   * @param {BarberShopUpsertArgs} args - Arguments to update or create a BarberShop.
   * @example
   * // Update or create a BarberShop
   * const barberShop = await prisma.barberShop.upsert({
   *   create: {
   *     // ... data to create a BarberShop
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BarberShop we want to update
   *   }
   * })
   */
  upsert<T extends BarberShopUpsertArgs>(args: Prisma.SelectSubset<T, BarberShopUpsertArgs<ExtArgs>>): Prisma.Prisma__BarberShopClient<runtime.Types.Result.GetResult<Prisma.$BarberShopPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BarberShops.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarberShopCountArgs} args - Arguments to filter BarberShops to count.
   * @example
   * // Count the number of BarberShops
   * const count = await prisma.barberShop.count({
   *   where: {
   *     // ... the filter for the BarberShops we want to count
   *   }
   * })
  **/
  count<T extends BarberShopCountArgs>(
    args?: Prisma.Subset<T, BarberShopCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BarberShopCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BarberShop.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarberShopAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BarberShopAggregateArgs>(args: Prisma.Subset<T, BarberShopAggregateArgs>): Prisma.PrismaPromise<GetBarberShopAggregateType<T>>

  /**
   * Group by BarberShop.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarberShopGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BarberShopGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BarberShopGroupByArgs['orderBy'] }
      : { orderBy?: BarberShopGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BarberShopGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBarberShopGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BarberShop model
 */
readonly fields: BarberShopFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BarberShop.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BarberShopClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  owner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  services<T extends Prisma.BarberShop$servicesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BarberShop$servicesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  bookings<T extends Prisma.BarberShop$bookingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BarberShop$bookingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BarberShop model
 */
export interface BarberShopFieldRefs {
  readonly id: Prisma.FieldRef<"BarberShop", 'String'>
  readonly name: Prisma.FieldRef<"BarberShop", 'String'>
  readonly slug: Prisma.FieldRef<"BarberShop", 'String'>
  readonly address: Prisma.FieldRef<"BarberShop", 'String'>
  readonly phone: Prisma.FieldRef<"BarberShop", 'String'>
  readonly imageUrl: Prisma.FieldRef<"BarberShop", 'String'>
  readonly ownerId: Prisma.FieldRef<"BarberShop", 'String'>
  readonly createdAt: Prisma.FieldRef<"BarberShop", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BarberShop", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BarberShop findUnique
 */
export type BarberShopFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * Filter, which BarberShop to fetch.
   */
  where: Prisma.BarberShopWhereUniqueInput
}

/**
 * BarberShop findUniqueOrThrow
 */
export type BarberShopFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * Filter, which BarberShop to fetch.
   */
  where: Prisma.BarberShopWhereUniqueInput
}

/**
 * BarberShop findFirst
 */
export type BarberShopFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * Filter, which BarberShop to fetch.
   */
  where?: Prisma.BarberShopWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarberShops to fetch.
   */
  orderBy?: Prisma.BarberShopOrderByWithRelationInput | Prisma.BarberShopOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BarberShops.
   */
  cursor?: Prisma.BarberShopWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarberShops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarberShops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BarberShops.
   */
  distinct?: Prisma.BarberShopScalarFieldEnum | Prisma.BarberShopScalarFieldEnum[]
}

/**
 * BarberShop findFirstOrThrow
 */
export type BarberShopFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * Filter, which BarberShop to fetch.
   */
  where?: Prisma.BarberShopWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarberShops to fetch.
   */
  orderBy?: Prisma.BarberShopOrderByWithRelationInput | Prisma.BarberShopOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BarberShops.
   */
  cursor?: Prisma.BarberShopWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarberShops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarberShops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BarberShops.
   */
  distinct?: Prisma.BarberShopScalarFieldEnum | Prisma.BarberShopScalarFieldEnum[]
}

/**
 * BarberShop findMany
 */
export type BarberShopFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * Filter, which BarberShops to fetch.
   */
  where?: Prisma.BarberShopWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarberShops to fetch.
   */
  orderBy?: Prisma.BarberShopOrderByWithRelationInput | Prisma.BarberShopOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BarberShops.
   */
  cursor?: Prisma.BarberShopWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarberShops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarberShops.
   */
  skip?: number
  distinct?: Prisma.BarberShopScalarFieldEnum | Prisma.BarberShopScalarFieldEnum[]
}

/**
 * BarberShop create
 */
export type BarberShopCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * The data needed to create a BarberShop.
   */
  data: Prisma.XOR<Prisma.BarberShopCreateInput, Prisma.BarberShopUncheckedCreateInput>
}

/**
 * BarberShop createMany
 */
export type BarberShopCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BarberShops.
   */
  data: Prisma.BarberShopCreateManyInput | Prisma.BarberShopCreateManyInput[]
}

/**
 * BarberShop createManyAndReturn
 */
export type BarberShopCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * The data used to create many BarberShops.
   */
  data: Prisma.BarberShopCreateManyInput | Prisma.BarberShopCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BarberShop update
 */
export type BarberShopUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * The data needed to update a BarberShop.
   */
  data: Prisma.XOR<Prisma.BarberShopUpdateInput, Prisma.BarberShopUncheckedUpdateInput>
  /**
   * Choose, which BarberShop to update.
   */
  where: Prisma.BarberShopWhereUniqueInput
}

/**
 * BarberShop updateMany
 */
export type BarberShopUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BarberShops.
   */
  data: Prisma.XOR<Prisma.BarberShopUpdateManyMutationInput, Prisma.BarberShopUncheckedUpdateManyInput>
  /**
   * Filter which BarberShops to update
   */
  where?: Prisma.BarberShopWhereInput
  /**
   * Limit how many BarberShops to update.
   */
  limit?: number
}

/**
 * BarberShop updateManyAndReturn
 */
export type BarberShopUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * The data used to update BarberShops.
   */
  data: Prisma.XOR<Prisma.BarberShopUpdateManyMutationInput, Prisma.BarberShopUncheckedUpdateManyInput>
  /**
   * Filter which BarberShops to update
   */
  where?: Prisma.BarberShopWhereInput
  /**
   * Limit how many BarberShops to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BarberShop upsert
 */
export type BarberShopUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * The filter to search for the BarberShop to update in case it exists.
   */
  where: Prisma.BarberShopWhereUniqueInput
  /**
   * In case the BarberShop found by the `where` argument doesn't exist, create a new BarberShop with this data.
   */
  create: Prisma.XOR<Prisma.BarberShopCreateInput, Prisma.BarberShopUncheckedCreateInput>
  /**
   * In case the BarberShop was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BarberShopUpdateInput, Prisma.BarberShopUncheckedUpdateInput>
}

/**
 * BarberShop delete
 */
export type BarberShopDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
  /**
   * Filter which BarberShop to delete.
   */
  where: Prisma.BarberShopWhereUniqueInput
}

/**
 * BarberShop deleteMany
 */
export type BarberShopDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BarberShops to delete
   */
  where?: Prisma.BarberShopWhereInput
  /**
   * Limit how many BarberShops to delete.
   */
  limit?: number
}

/**
 * BarberShop.services
 */
export type BarberShop$servicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  where?: Prisma.ServiceWhereInput
  orderBy?: Prisma.ServiceOrderByWithRelationInput | Prisma.ServiceOrderByWithRelationInput[]
  cursor?: Prisma.ServiceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServiceScalarFieldEnum | Prisma.ServiceScalarFieldEnum[]
}

/**
 * BarberShop.bookings
 */
export type BarberShop$bookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Booking
   */
  select?: Prisma.BookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Booking
   */
  omit?: Prisma.BookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingInclude<ExtArgs> | null
  where?: Prisma.BookingWhereInput
  orderBy?: Prisma.BookingOrderByWithRelationInput | Prisma.BookingOrderByWithRelationInput[]
  cursor?: Prisma.BookingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BookingScalarFieldEnum | Prisma.BookingScalarFieldEnum[]
}

/**
 * BarberShop without action
 */
export type BarberShopDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarberShop
   */
  select?: Prisma.BarberShopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarberShop
   */
  omit?: Prisma.BarberShopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarberShopInclude<ExtArgs> | null
}
